title: "Hendrik - PSD"
author: "M. Hendrik Purwanto (240411100118)"
logo: "_static/avatar.jpeg"

execute:
  execute_notebooks: "off"   # notebook dijalankan manual dulu, book hanya render outputnya

repository:
  url: https://github.com/hendprw/psd
  branch: main

html:
  use_repository_button: true
  use_issues_button: true

sphinx:
  config:
    html_theme: sphinx_book_theme